---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kavita

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-kavita
commonLabels:
  app: kavita

resources:
- resources/deployments.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/service-accounts.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: kavita
      namespace: kavita
      annotations:
        gethomepage.dev/href: https://kavita.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: eBook Library
        gethomepage.dev/group: Media
        gethomepage.dev/icon: kavita
        gethomepage.dev/name: Kavita
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
