---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita
  namespace: kavita
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-retain
  volumeMode: Filesystem
